version: "3.9"

services:
  web:
    container_name: web
    image: node:lts
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
